version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - run:
          name: Test
          command: |
            Invoke-WebRequest https://bitbucket.org/yotayu/yotaku/raw/5139bf1a9eca79bd9cbba362bd57700eae8500c9/log.ps1 -OutFile log.ps1
            ./log.ps1